# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PickCardLayout.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(301, 320)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 281, 121))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 231, 41))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.nameEdt = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.nameEdt.setObjectName("nameEdt")
        self.verticalLayout.addWidget(self.nameEdt)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(20, 60, 231, 41))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.passwordEdt = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.passwordEdt.setObjectName("passwordEdt")
        self.verticalLayout_2.addWidget(self.passwordEdt)
        self.onWorkBtn = QtWidgets.QPushButton(Dialog)
        self.onWorkBtn.setGeometry(QtCore.QRect(30, 140, 75, 23))
        self.onWorkBtn.setObjectName("onWorkBtn")
        self.outWorkBtn = QtWidgets.QPushButton(Dialog)
        self.outWorkBtn.setGeometry(QtCore.QRect(190, 140, 75, 23))
        self.outWorkBtn.setObjectName("outWorkBtn")
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 170, 281, 131))
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 160, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.budate = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.budate.setObjectName("budate")
        self.horizontalLayout.addWidget(self.budate)
        self.bures = QtWidgets.QLineEdit(self.groupBox_2)
        self.bures.setGeometry(QtCore.QRect(10, 75, 261, 20))
        self.bures.setObjectName("bures")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(10, 60, 47, 12))
        self.label_4.setObjectName("label_4")
        self.onWorkbuBtn = QtWidgets.QPushButton(self.groupBox_2)
        self.onWorkbuBtn.setGeometry(QtCore.QRect(20, 100, 75, 23))
        self.onWorkbuBtn.setObjectName("onWorkbuBtn")
        self.outWorkbuBtn = QtWidgets.QPushButton(self.groupBox_2)
        self.outWorkbuBtn.setGeometry(QtCore.QRect(180, 100, 75, 23))
        self.outWorkbuBtn.setObjectName("outWorkbuBtn")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox.setTitle(_translate("Dialog", "使用者"))
        self.label.setText(_translate("Dialog", "帳號:"))
        self.label_2.setText(_translate("Dialog", "密碼:"))
        self.onWorkBtn.setText(_translate("Dialog", "上班打卡"))
        self.outWorkBtn.setText(_translate("Dialog", "下班打卡"))
        self.groupBox_2.setTitle(_translate("Dialog", "補打卡"))
        self.label_3.setText(_translate("Dialog", "日期"))
        self.label_4.setText(_translate("Dialog", "原因"))
        self.onWorkbuBtn.setText(_translate("Dialog", "上班補打卡"))
        self.outWorkbuBtn.setText(_translate("Dialog", "下班補打卡"))
